name: Check Upstream Repository
on:
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: 'Upstream repository branch name'
        required: false
        default: master
  schedule:
    - cron: '0 * * * *' # Runs every hour
jobs:
  check_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Fetch upstream
        run: git fetch --depth 1 ${{ secrets.UPSTREAM_REPO_URL }} ${{ github.event.inputs.upstream_branch || 'master' }}:upstream
      - name: Get upstream commit ID
        id: get-upstream-commit
        run: echo "commit_id=$(git rev-parse upstream)" >> $GITHUB_OUTPUT

      - name: Restore last upstream commit ID from cache
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: last_upstream_commit.txt
          key: last-upstream-commit-${{ github.run_id }} # Use run_id for per-run isolation
          restore-keys: |
            last-upstream-commit-

      - name: Get last known commit id
        id: get-last-commit
        run: echo "last_commit_id=$(cat last_upstream_commit.txt || echo '')" >> $GITHUB_OUTPUT

      - name: Dispatch event if updates are found
        if: steps.get-upstream-commit.outputs.commit_id != steps.get-last-commit.outputs.last_commit_id
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: upstream_repository_updated

      - name: Save current upstream commit id
        if: steps.get-upstream-commit.outputs.commit_id != steps.get-last-commit.outputs.last_commit_id
        run: echo ${{steps.get-upstream-commit.outputs.commit_id}} > last_upstream_commit.txt

      - name: Save last upstream commit ID to cache
        id: cache-save
        if: steps.get-upstream-commit.outputs.commit_id != steps.get-last-commit.outputs.last_commit_id
        uses: actions/cache/save@v3
        with:
          path: last_upstream_commit.txt
          key: last-upstream-commit-${{ github.run_id }}

      - name: Delete expired cache
        if: steps.get-upstream-commit.outputs.commit_id != steps.get-last-commit.outputs.last_commit_id
        uses: actions/github-script@v6
        with:
          script: |
            const { data: { id: cacheId } } = await github.rest.actions.getActionsCacheUsage();
            if (cacheId) {
              await github.rest.actions.deleteActionsCacheById({
                cache_id: cacheId
              });
            }
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
            retain_days: 0
            keep_minimum_runs: 2
